
###
# requests/api.http

# Send Request
POST http://127.0.0.1:8000/api/auth/register
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Smith",
  "email": "john@example.com",
  "password": "1234"
}